# One sensor adapter instance per sensor-machine link.

{% if module_enabled_out == true %}
module_enabled = true
{% else %}
module_enabled = false
{% endif %}

input_broker = "{{sensor_broker}}"  # this path required by MQTTTrigger. Otherwise I would put it under [sensor]

[sensor]
topic = "{{sensor_mqtt_topic}}"


[thresholds]
parameter = "{{mqtt_payload_json_key}}"
value = {{threshold_value}}
# Comparison is hard-coded to running when parameter is greater than value

[output]
target = "{{machine_uuid}}"
# Always output to broker mqtt.docker.local, not configurable
